[package]
name = "rust_test_project"
version = "0.1.0"
authors = ["Yolan Uyttenhove <yuyttenhove@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3.1"
image = "0.23.12"
